### ISSUE TITLE
Demo on demo.classlab.org

### ISSUE THREAD

**Issue by schurig** [classlab/classlab#10]
- [x] Build docker container (postgres, nginx and elixir app in the same container)
- [ ] deploy it to demo.classlab.org
- [ ] let it rebuild and deploy on each push to master

**Comment by sbrink** [comment]
Maybe we could use this as foundation: https://github.com/coders51/docker-elixir-postgres

**Comment by sbrink** [comment]
Here's another tutorial: http://blog.jonharrington.org/elixir-and-docker/
